CREATE ROLE backend_user WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD '12345';

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "public" TO backend_user;
GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA "public" TO backend_user;
